# Generated by Django 5.2.8 on 2026-01-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='number_of_beds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
