# Generated by Django 5.2.8 on 2026-01-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0002_dormitory_number_of_beds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormitory',
            old_name='number_of_beds',
            new_name='beds',
        ),
    ]
