# Generated by Django 5.2.8 on 2026-01-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0003_rename_number_of_beds_dormitory_beds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormitory',
            old_name='beds',
            new_name='total_beds',
        ),
    ]
