# Generated by Django 5.2.8 on 2026-01-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0004_rename_beds_dormitory_total_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='room_prefix',
            field=models.CharField(default='A', help_text="Prefix for room numbers (e.g., 'A' for A1, A2...)", max_length=10),
        ),
    ]
