# Generated by Django 5.2.8 on 2026-02-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0005_dormitory_room_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=2),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='type',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=2),
        ),
    ]
