# Generated by Django 5.2.8 on 2026-01-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Quad', 'Quad')], default='Double', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='total_beds',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
