# Generated by Django 5.2.8 on 2026-01-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_total_beds_room_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
