# Generated by Django 5.2.8 on 2026-01-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardenprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10),
        ),
    ]
