# Generated by Django 5.2.8 on 2026-01-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wardenprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('UG', 'Ug'), ('PG', 'Pg')], max_length=10),
        ),
    ]
