# Generated by Django 5.2.8 on 2026-01-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='can_change_room',
            field=models.BooleanField(default=False),
        ),
    ]
