# Generated by Django 5.2.8 on 2026-02-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
