# Generated by Django 5.2.8 on 2026-01-10 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_gender'),
        ('dormitories', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='dormitories.dormitory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorm_applications', to='accounts.studentprofile')),
            ],
        ),
    ]
