# Generated by Django 5.2.8 on 2026-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_dormapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormapplication',
            name='room_preference',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=20, null=True),
        ),
    ]
