# Generated by Django 5.2.8 on 2026-02-04 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_studentprofile_can_change_room'),
        ('dormitories', '0005_dormitory_room_prefix'),
        ('rooms', '0005_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_preference', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='dormitories.dormitory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorm_applications', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'requests_dormapplication',
            },
        ),
        migrations.CreateModel(
            name='NewStudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_preference', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_student_requests', to='dormitories.dormitory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_student_requests', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'requests_newstudentrequest',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_preference', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('current_bed_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_requests', to='rooms.room')),
                ('preferred_dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_change_requests', to='dormitories.dormitory')),
                ('preferred_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_requests', to='rooms.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'requests_request',
            },
        ),
    ]
