# Generated by Django 5.2.8 on 2026-02-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
